version: '3.5'

services:
  db-postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_chat
    container_name: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ../init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
  be:
    container_name: app-chat-be
    environment:
      - NODE_ENV=dev
      - APP_PORT=8080
      - POSTGRES_HOST=db-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_chat
      - DB_SCHEMA=dev
      - SECRET_JWT=giabao123
      - JWT_EXPIRES_IN=1d
    #      - NODE_ENV=dev
    #      - APP_PORT=8080
    #      - POSTGRES_HOST=localhost
    #      - POSTGRES_PORT=5432
    #      - POSTGRES_USER=root
    #      - POSTGRES_PASSWORD=postgres
    #      - POSTGRES_DB=app_chat
    #      - DB_SCHEMA=dev
    #      - SECRET_JWT=giabao123
    #      - JWT_EXPIRES_IN=1d
    build:
      dockerfile: Dockerfile
      context: ../
    restart: unless-stopped
    depends_on:
      - db-postgres
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    depends_on:
      - db-postgres
volumes:
  pg-data:
    name: pg-data