# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  # build:

  #   runs-on: self-hosted
  #   name: Countinous Intergration Test 
  #   steps: 
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v1
  #     with:
  #       node-version: 18

  docker_build: 
    runs-on: self-hosted
    name: Docker Image Build And Push 
    # needs: [build]
    steps:
      - name: Log Docker Hub Username
        env: 
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: echo $username - $password
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          # username: ${{ secrets.DOCKER_USERNAME }}
          # password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
           username: giabao0403
           password: dckr_pat_DawHkX61q9UjSsT11HJ1LK-wa9k
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app-chat-be:latest
  deploy:
    runs-on: ubuntu-latest
    name: Continuous Deployment
    needs: [docker_build]
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            docker stop app-chat-be;
            docker rm app-chat-be;
            docker pull ${{ secrets.DOCKER_USERNAME }}/app-chat-be:latest;
            docker-compose up -d


